import { HistoricalEvent } from '@components/App/types';

export const historicalEvents: HistoricalEvent[] = [
  {
    id: 'event-1',
    start: 1900,
    end: 1910,
    title: 'Наука',
    children: [
      {
        id: 'child-1-1',
        year: 1900,
        description: 'Георг Кантор публикует работы по множествам',
      },
      {
        id: 'child-1-2',
        year: 1901,
        description: 'Нобелевская премия впервые вручается',
      },
      { id: 'child-1-3', year: 1903, description: 'Первый успешный полёт братьев Райт' },
      {
        id: 'child-1-4',
        year: 1905,
        description: 'Эйнштейн публикует теорию относительности',
      },
      { id: 'child-1-5', year: 1908, description: 'Падение Тунгусского метеорита' },
      { id: 'child-1-6', year: 1909, description: 'Первая пересадка органов у животных' },
    ],
  },
  {
    id: 'event-2',
    start: 1910,
    end: 1920,
    title: 'Искусство',
    children: [
      { id: 'child-2-1', year: 1910, description: 'Импрессионизм на пике популярности' },
      { id: 'child-2-2', year: 1911, description: 'Похищение Джоконды' },
      { id: 'child-2-3', year: 1913, description: "Премьера балета 'Весна священная'" },
      { id: 'child-2-4', year: 1915, description: 'Развитие футуризма в Италии' },
      { id: 'child-2-5', year: 1918, description: 'Появление дадаизма' },
      { id: 'child-2-6', year: 1919, description: 'Основание школы Баухаус' },
    ],
  },
  {
    id: 'event-3',
    start: 1920,
    end: 1930,
    title: 'Технологии',
    children: [
      { id: 'child-3-1', year: 1920, description: 'Создание первых радиостанций' },
      { id: 'child-3-2', year: 1921, description: 'Изобретение телевидения' },
      { id: 'child-3-3', year: 1923, description: 'Развитие авиации' },
      { id: 'child-3-4', year: 1924, description: 'Телеграф через Атлантику' },
      { id: 'child-3-5', year: 1927, description: "Первый звуковой фильм 'Певец джаза'" },
      { id: 'child-3-6', year: 1928, description: 'Открытие пенициллина' },
      { id: 'child-3-7', year: 1929, description: 'Массовое производство автомобилей' },
    ],
  },
  {
    id: 'event-4',
    start: 1930,
    end: 1940,
    title: 'Политика',
    children: [
      { id: 'child-4-1', year: 1930, description: 'Великая депрессия' },
      {
        id: 'child-4-2',
        year: 1933,
        description: 'Гитлер становится канцлером Германии',
      },
      { id: 'child-4-3', year: 1936, description: 'Гражданская война в Испании' },
      { id: 'child-4-4', year: 1938, description: 'Аншлюс Австрии' },
      { id: 'child-4-5', year: 1939, description: 'Начало Второй мировой войны' },
    ],
  },
  {
    id: 'event-5',
    start: 1940,
    end: 1950,
    title: 'Наука и техника',
    children: [
      { id: 'child-5-1', year: 1942, description: 'Манхэттенский проект' },
      { id: 'child-5-2', year: 1945, description: 'Создание атомной бомбы' },
      { id: 'child-5-3', year: 1946, description: 'Первые электронные компьютеры' },
      { id: 'child-5-4', year: 1947, description: 'Изобретение транзистора' },
      { id: 'child-5-5', year: 1949, description: 'Открытие структуры ДНК' },
    ],
  },
  {
    id: 'event-6',
    start: 1950,
    end: 1960,
    title: 'Технологии',
    children: [
      { id: 'child-6-1', year: 1950, description: 'Первые коммерческие компьютеры' },
      { id: 'child-6-2', year: 1954, description: 'Первая пересадка органов человеку' },
      { id: 'child-6-3', year: 1957, description: 'Запуск спутника Спутник-1' },
      { id: 'child-6-4', year: 1958, description: 'Создание NASA' },
      { id: 'child-6-5', year: 1959, description: 'Появление лазеров' },
    ],
  },
  {
    id: 'event-7',
    start: 1960,
    end: 1970,
    title: 'Культура',
    children: [
      { id: 'child-7-1', year: 1961, description: 'Первый полёт Гагарина' },
      { id: 'child-7-2', year: 1963, description: 'Речь Мартина Лютера Кинга' },
      { id: 'child-7-3', year: 1965, description: 'Расцвет рок-музыки' },
      { id: 'child-7-4', year: 1967, description: 'Развитие телекоммуникаций' },
      { id: 'child-7-5', year: 1969, description: 'Высадка человека на Луну' },
    ],
  },
  {
    id: 'event-8',
    start: 1970,
    end: 1980,
    title: 'Технологии',
    children: [
      { id: 'child-8-1', year: 1971, description: 'Первый микропроцессор Intel 4004' },
      { id: 'child-8-2', year: 1973, description: 'Первый мобильный телефон' },
      { id: 'child-8-3', year: 1975, description: 'Основание Microsoft' },
      { id: 'child-8-4', year: 1976, description: 'Основание Apple' },
      { id: 'child-8-5', year: 1979, description: 'Появление графических интерфейсов' },
    ],
  },
  {
    id: 'event-9',
    start: 1980,
    end: 1990,
    title: 'Наука',
    children: [
      { id: 'child-9-1', year: 1981, description: 'Первый полёт шаттла' },
      { id: 'child-9-2', year: 1983, description: 'Введение протокола TCP/IP' },
      { id: 'child-9-3', year: 1985, description: 'Развитие генетической инженерии' },
      { id: 'child-9-4', year: 1986, description: 'Чернобыльская катастрофа' },
      { id: 'child-9-5', year: 1989, description: 'Падение Берлинской стены' },
    ],
  },
  {
    id: 'event-10',
    start: 1990,
    end: 2000,
    title: 'Культура и технологии',
    children: [
      {
        id: 'child-10-1',
        year: 1990,
        description: 'Начало массового использования интернета',
      },
      { id: 'child-10-2', year: 1991, description: 'Создание WWW' },
      { id: 'child-10-3', year: 1993, description: 'Появление первых веб-браузеров' },
      { id: 'child-10-4', year: 1995, description: 'Выход Windows 95' },
      { id: 'child-10-5', year: 1998, description: 'Основание Google' },
      {
        id: 'child-10-6',
        year: 1999,
        description: 'Распространение интернета в массовую культуру',
      },
    ],
  },
];
